services:
  backend:
    build:
      context: ./backend
    environment:
      PORT: 3000
      NODE_ENV: production
      CORS_ORIGIN: http://localhost
    ports:
      - '3000:3000'

  frontend:
    build:
      context: ./frontend
    ports:
      - '8080:80'
    depends_on:
      - backend
